services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.stable
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    networks:
      - pokesleep-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.stable
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - pokesleep-network

networks:
  pokesleep-network:
    driver: bridge